// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVdttwwM9Iv_PbsOpK8Ttm2NJlcLzwSDM',
    appId: '1:264300022400:web:5ab2e5c5639ed8547ab465',
    messagingSenderId: '264300022400',
    projectId: 'todoapp-a1d6e',
    authDomain: 'todoapp-a1d6e.firebaseapp.com',
    storageBucket: 'todoapp-a1d6e.appspot.com',
    measurementId: 'G-EQXTL1JF78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyvcJiPV7_cWJAJJM8r2Oba6niQis9sNc',
    appId: '1:264300022400:android:f7caa9a374f2263a7ab465',
    messagingSenderId: '264300022400',
    projectId: 'todoapp-a1d6e',
    storageBucket: 'todoapp-a1d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gieH2nd1SyKkfhTDh4k8ZB4fhWEIULE',
    appId: '1:264300022400:ios:d0877598404332d27ab465',
    messagingSenderId: '264300022400',
    projectId: 'todoapp-a1d6e',
    storageBucket: 'todoapp-a1d6e.appspot.com',
    iosBundleId: 'com.murtazaagaz.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gieH2nd1SyKkfhTDh4k8ZB4fhWEIULE',
    appId: '1:264300022400:ios:7e04639b08b150a77ab465',
    messagingSenderId: '264300022400',
    projectId: 'todoapp-a1d6e',
    storageBucket: 'todoapp-a1d6e.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVdttwwM9Iv_PbsOpK8Ttm2NJlcLzwSDM',
    appId: '1:264300022400:web:1c363ce26535c6667ab465',
    messagingSenderId: '264300022400',
    projectId: 'todoapp-a1d6e',
    authDomain: 'todoapp-a1d6e.firebaseapp.com',
    storageBucket: 'todoapp-a1d6e.appspot.com',
    measurementId: 'G-TN6QC55QNE',
  );
}
